[profile.default]
solc_version = '0.8.13'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200 # Default amount
test = 'test'
src = 'src'
out = 'out'

libs = ['lib']

[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"

[etherscan]
polygon = { key = "${POLYGONSCAN_API_KEY}" }